import { StyleSheet } from 'react-native';

export const Styles = StyleSheet.create({
	container: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: 'rgba(5,5,5,0.90)',
		color: '#43ca83',
	},
	buttonContainer: {
		flexDirection: 'row',
		justifyContent: 'space-evenly',
		position: 'absolute',
		top: 680,
		marginTop: 20,
		marginHorizontal: 20,
		width: 324,
	},
	indextext: {
		fontFamily: 'Poppins-Medium',
		fontSize: 22,
		color: '#FCFCFC',
		position: 'absolute',
		left: 309,
		top: 80,
	},
	submitbtn: {
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#FCFCFC',
		marginBottom: 10,
		width: 80,
		height: 40,
		borderRadius: 10,
		top: 198,
		left: 21,
		position: 'absolute',
	},
	btntext: {
		fontSize: 13,
		color: '#0A0A0A',
		fontFamily: 'Poppins-Medium',
	},
	board: {
		position: 'absolute',
		top: 300,
	},
	movelist: {
		width: 336,
		height: 24,
		position: 'absolute',
		top: 647,
		backgroundColor: '#DADADA12',
		borderRadius: 13,
		borderWidth: 1,
		borderColor: '#E5E5E525',
	},
	movestext: {
		color: '#C4C4C4',
		fontSize: 11,
		paddingHorizontal: 10,
		fontFamily: 'Roboto-Medium',
		alignSelf: 'center',
	},
	inputfield: {
		borderBottomColor: '#E5E5E551',
		borderBottomWidth: 2,
		width: 330,
		position: 'absolute',
		top: 159,
		color: '#FCFCFC',
		fontFamily: 'Roboto-Medium',
		fontSize: 14,
		paddingBottom: 10,
	},
});
